In [1]:
#Load your dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv(r"C:\Users\Dell\Downloads\owid-co2-data.csv")
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Understand your data
df.columns        # lists all column names

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='object')

In [5]:
df.shape          # tells you number of rows & columns

(50191, 79)

df.info()         # tells you column data types and missing values

In [13]:
df.describe()     # gives basic statistics

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50191.000000,4.101900e+04,1.525100e+04,28863.000000,25358.000000,29137.000000,26981.000000,26002.000000,23585.000000,23285.000000,...,2108.000000,41001.000000,38060.000000,41001.000000,41001.000000,38060.000000,37410.000000,37236.000000,4535.000000,4535.000000
mean,1919.883067,5.686141e+07,3.300495e+11,7.767746,0.059036,415.698178,6.208882,43.104462,535.581202,7.214604,...,7.512655,2.269285,0.003026,0.007670,0.011023,0.000509,488.542225,316.133529,-7.232399,20.524440
std,65.627296,3.199905e+08,3.086383e+12,62.595292,0.120328,1945.843973,62.322553,1729.939596,2202.219657,99.347980,...,17.671054,9.315325,0.016519,0.043694,0.061901,0.003043,2392.579910,1839.602293,250.640012,52.744956
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1977.750000,-100.000000,-99.693000,-2325.500000,...,0.000000,-0.810000,-0.001000,0.000000,-0.001000,0.000000,-14.961000,0.000000,-2195.952000,-98.849000
25%,1875.000000,3.273130e+05,7.874038e+09,0.000000,0.000000,0.374000,-0.005000,-1.102500,6.418000,-0.908000,...,0.204750,0.004000,0.000000,0.000000,0.000000,0.000000,1.835000,0.235000,-3.179500,-6.168000
50%,1924.000000,2.289522e+06,2.743861e+10,0.000000,0.001000,4.990000,0.044000,3.803500,27.691000,0.078000,...,0.838000,0.078000,0.000000,0.000000,0.000000,0.000000,15.007500,2.371000,1.518000,8.701000
75%,1974.000000,9.862459e+06,1.212627e+11,0.486000,0.075750,53.273000,1.002000,10.890750,123.959000,2.620000,...,3.211000,0.359000,0.001000,0.001000,0.001000,0.000000,78.242750,29.337500,9.153500,32.666000
max,2023.000000,8.091735e+09,1.301126e+14,1696.308000,2.484000,37791.570000,1865.208000,180870.000000,41416.480000,2340.184000,...,100.000000,100.000000,0.422000,1.161000,1.668000,0.085000,53816.852000,44114.785000,1798.999000,568.635000

In [15]:
df.dtypes

country                         object
year                             int64
iso_code                        object
population                     float64
gdp                            float64
                                ...
temperature_change_from_n2o    float64
total_ghg                      float64
total_ghg_excluding_lucf       float64
trade_co2                      float64
trade_co2_share                float64
Length: 79, dtype: object

In [17]:
df.nunique()

country                          255
year                             274
iso_code                         218
population                     40052
gdp                            15248
                               ...
temperature_change_from_n2o       80
total_ghg                      26232
total_ghg_excluding_lucf       18603
trade_co2                       4166
trade_co2_share                 4319
Length: 79, dtype: int64

In [31]:
# Columns to drop
columns_to_drop = [
    'trade_co2','trade_co2_share',
    'temperature_change_from_ch4','temperature_change_from_co2',
    'temperature_change_from_ghg','temperature_change_from_n2o',
    'total_ghg','total_ghg_excluding_lucf'
]

# Drop only if they exist
columns_to_drop = [c for c in columns_to_drop if c in df.columns]
df = df.drop(columns=columns_to_drop)
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg
0,Afghanistan,1750,AFG,2802560.0,NaN,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,...,NaN,0.274,0.025,NaN,0.0,NaN,0.252,0.030,NaN,0.106
50187,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,...,NaN,0.274,0.025,NaN,0.0,NaN,0.260,0.028,NaN,0.105
50188,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,...,NaN,0.274,0.025,NaN,0.0,NaN,0.241,0.032,NaN,0.104
50189,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,...,NaN,0.273,0.025,NaN,0.0,NaN,0.227,0.028,NaN,0.103
50190,Zimbabwe,2023,ZWE,16340829.0,NaN,0.531,0.032,11.164,0.739,7.090,...,NaN,0.273,0.025,NaN,0.0,NaN,0.204,0.028,NaN,0.102

In [25]:
df.dtypes

country                                  object
year                                      int64
iso_code                                 object
population                              float64
gdp                                     float64
                                         ...
share_global_gas_co2                    float64
share_global_luc_co2                    float64
share_global_oil_co2                    float64
share_global_other_co2                  float64
share_of_temperature_change_from_ghg    float64
Length: 71, dtype: object

In [33]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(numeric_cols)

['year', 'population', 'gdp', 'cement_co2', 'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct', 'co2_including_luc', 'co2_including_luc_growth_abs', 'co2_including_luc_growth_prct', 'co2_including_luc_per_capita', 'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2', 'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita', 'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2', 'cumulative_co2_including_luc', 'cumulative_coal_co2', 'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2', 'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita', 'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2', 'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita', 'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita', 'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita', 'other_industry_co2', 'primary_energy_consumption', 'share_global_cement_co2', 'share_global_co2', 'share_global_co2_including_luc', 'share_global_coal_co2', 'share_global_cumulative_cement_co2', 'share_global_cumulative_co2', 'share_global_cumulative_co2_including_luc', 'share_global_cumulative_coal_co2', 'share_global_cumulative_flaring_co2', 'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2', 'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2', 'share_global_flaring_co2', 'share_global_gas_co2', 'share_global_luc_co2', 'share_global_oil_co2', 'share_global_other_co2', 'share_of_temperature_change_from_ghg']

In [36]:
for i in ['year', 'population', 'gdp', 'cement_co2', 'cement_co2_per_capita', 
                'co2', 'co2_growth_abs', 'co2_growth_prct', 'co2_including_luc', 
                'co2_including_luc_growth_abs', 'co2_including_luc_growth_prct', 
                'co2_including_luc_per_capita', 'co2_including_luc_per_gdp', 
                'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp', 
                'co2_per_unit_energy', 'coal_co2', 'coal_co2_per_capita', 'consumption_co2', 
                'consumption_co2_per_capita', 'consumption_co2_per_gdp', 'cumulative_cement_co2', 
                'cumulative_co2', 'cumulative_co2_including_luc', 'cumulative_coal_co2', 
                'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2', 
                'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita', 'energy_per_gdp', 
                'flaring_co2', 'flaring_co2_per_capita', 'gas_co2', 'gas_co2_per_capita', 
                'ghg_excluding_lucf_per_capita', 'ghg_per_capita', 'land_use_change_co2', 
                'land_use_change_co2_per_capita', 'methane', 'methane_per_capita', 'nitrous_oxide', 
                'nitrous_oxide_per_capita', 'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita', 
                'other_industry_co2', 'primary_energy_consumption', 'share_global_cement_co2', 
                'share_global_co2', 'share_global_co2_including_luc', 'share_global_coal_co2', 
                'share_global_cumulative_cement_co2', 'share_global_cumulative_co2', 
                'share_global_cumulative_co2_including_luc', 'share_global_cumulative_coal_co2', 
                'share_global_cumulative_flaring_co2', 'share_global_cumulative_gas_co2', 
                'share_global_cumulative_luc_co2', 'share_global_cumulative_oil_co2', 
                'share_global_cumulative_other_co2', 'share_global_flaring_co2', 'share_global_gas_co2', 
                'share_global_luc_co2', 'share_global_oil_co2', 'share_global_other_co2', 
                'share_of_temperature_change_from_ghg']:
       df[i]=df[i].fillna(df[i].median())

In [38]:
df.isnull().sum()

country                                    0
year                                       0
iso_code                                7929
population                                 0
gdp                                        0
                                        ...
share_global_gas_co2                       0
share_global_luc_co2                       0
share_global_oil_co2                       0
share_global_other_co2                     0
share_of_temperature_change_from_ghg       0
Length: 71, dtype: int64

In [42]:
object_cols = df.select_dtypes(include=['object']).columns.tolist()

for col in object_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg
0,Afghanistan,1750,AFG,2802560.0,2.743861e+10,0.000,0.000,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
1,Afghanistan,1751,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
2,Afghanistan,1752,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
3,Afghanistan,1753,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
4,Afghanistan,1754,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.4110,...,0.014,0.274,0.025,0.543,0.000,0.025,0.252,0.030,0.838,0.106
50187,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.2310,...,0.014,0.274,0.025,0.543,0.000,0.025,0.260,0.028,0.838,0.105
50188,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.1200,...,0.014,0.274,0.025,0.543,0.000,0.025,0.241,0.032,0.838,0.104
50189,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.1690,...,0.014,0.273,0.025,0.543,0.000,0.025,0.227,0.028,0.838,0.103
50190,Zimbabwe,2023,ZWE,16340829.0,2.743861e+10,0.531,0.032,11.164,0.739,7.0900,...,0.014,0.273,0.025,0.543,0.000,0.025,0.204,0.028,0.838,0.102

In [48]:
if 'Unnamed: 0' in df.columns:
    df.drop('Unnamed: 0', axis=1, inplace=True)

df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg
0,Afghanistan,1750,AFG,2802560.0,2.743861e+10,0.0,0.000,4.99,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
1,Afghanistan,1751,AFG,2289522.0,2.743861e+10,0.0,0.001,4.99,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
2,Afghanistan,1752,AFG,2289522.0,2.743861e+10,0.0,0.001,4.99,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
3,Afghanistan,1753,AFG,2289522.0,2.743861e+10,0.0,0.001,4.99,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
4,Afghanistan,1754,AFG,2289522.0,2.743861e+10,0.0,0.001,4.99,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078

In [50]:
df.isnull().sum()

country                                 0
year                                    0
iso_code                                0
population                              0
gdp                                     0
                                       ..
share_global_gas_co2                    0
share_global_luc_co2                    0
share_global_oil_co2                    0
share_global_other_co2                  0
share_of_temperature_change_from_ghg    0
Length: 71, dtype: int64

In [54]:
#Prepare per capita and per GDP metrics
df['co2_per_capita'] = df['co2'] / df['population']
df['co2_per_gdp'] = df['co2'] / (df['gdp'] / 1e6)  # divide GDP by 1M for scale
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg
0,Afghanistan,1750,AFG,2802560.0,2.743861e+10,0.000,0.000,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
1,Afghanistan,1751,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
2,Afghanistan,1752,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
3,Afghanistan,1753,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
4,Afghanistan,1754,AFG,2289522.0,2.743861e+10,0.000,0.001,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.4110,...,0.014,0.274,0.025,0.543,0.000,0.025,0.252,0.030,0.838,0.106
50187,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.2310,...,0.014,0.274,0.025,0.543,0.000,0.025,0.260,0.028,0.838,0.105
50188,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.1200,...,0.014,0.274,0.025,0.543,0.000,0.025,0.241,0.032,0.838,0.104
50189,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.1690,...,0.014,0.273,0.025,0.543,0.000,0.025,0.227,0.028,0.838,0.103
50190,Zimbabwe,2023,ZWE,16340829.0,2.743861e+10,0.531,0.032,11.164,0.739,7.0900,...,0.014,0.273,0.025,0.543,0.000,0.025,0.204,0.028,0.838,0.102

In [56]:
#Sector-wise per-capita metrics
sectors = ['cement_co2','coal_co2','oil_co2','gas_co2']
for s in sectors:
    df[f'{s}_per_capita'] = df[s] / df['population']
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_gas_co2,share_global_cumulative_luc_co2,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,share_of_temperature_change_from_ghg
0,Afghanistan,1750,AFG,2802560.0,2.743861e+10,0.000,0.000000e+00,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
1,Afghanistan,1751,AFG,2289522.0,2.743861e+10,0.000,0.000000e+00,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
2,Afghanistan,1752,AFG,2289522.0,2.743861e+10,0.000,0.000000e+00,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
3,Afghanistan,1753,AFG,2289522.0,2.743861e+10,0.000,0.000000e+00,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
4,Afghanistan,1754,AFG,2289522.0,2.743861e+10,0.000,0.000000e+00,4.990,0.044,3.8035,...,0.014,0.111,0.058,0.543,0.001,0.025,0.076,0.068,0.838,0.078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,3.097298e-08,10.263,-0.942,-8.4110,...,0.014,0.274,0.025,0.543,0.000,0.025,0.252,0.030,0.838,0.106
50187,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,3.194459e-08,8.495,-1.768,-17.2310,...,0.014,0.274,0.025,0.543,0.000,0.025,0.260,0.028,0.838,0.105
50188,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,3.361351e-08,10.204,1.709,20.1200,...,0.014,0.274,0.025,0.543,0.000,0.025,0.241,0.032,0.838,0.104
50189,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,3.304487e-08,10.425,0.221,2.1690,...,0.014,0.273,0.025,0.543,0.000,0.025,0.227,0.028,0.838,0.103
50190,Zimbabwe,2023,ZWE,16340829.0,2.743861e+10,0.531,3.249529e-08,11.164,0.739,7.0900,...,0.014,0.273,0.025,0.543,0.000,0.025,0.204,0.028,0.838,0.102

In [58]:
df.to_csv("cleaned_co2_data.csv", index=False)